controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    track_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    flipper_position_controller:
      type: position_controllers/JointGroupPositionController


track_velocity_controller:
  ros__parameters:
    joints:
      - FR_JOINT
      - FL_JOINT
      - BR_JOINT
      - BL_JOINT


flipper_position_controller:
  ros__parameters:
    joints:
      - FRF_joint
      - FLF_joint
      - BRF_joint
      - BLF_joint
