controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    flipper_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_state_broadcaster:
  ros__parameters: {}


flipper_position_controller:
  ros__parameters:
    joints:
      - FRF_joint
      - FLF_joint
      - BRF_joint
      - BLF_joint

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    open_loop_control: false
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 1.0

    gains:
      FRF_joint:
        p: 50.0
        i: 0.0
        d: 3.0
        i_clamp: 1.0

      FLF_joint:
        p: 50.0
        i: 0.0
        d: 3.0
        i_clamp: 1.0

      BRF_joint:
        p: 50.0
        i: 0.0
        d: 3.0
        i_clamp: 1.0

      BLF_joint:
        p: 50.0
        i: 0.0
        d: 3.0
        i_clamp: 1.0
